### PR TITLE
KM532 🐛 Fix setting zsh/bash shell environment variables

### PR DESCRIPTION
**Pull request by fredriv**
Fix a bug where setting the AWS_PROFILE would be overridden by the value set in the user's shell config files (`.zshrc` / `.bashrc`).

## Description

Instead of creating a local copy of the .zshrc config file to override "standard" environment variables like PS1 and AWS_PROFILE, we prevent the shell from reading the user configuration files by using the `-f` flag (and similarly `--norc` and `--noprofile` for bash).

## Motivation and Context

Fixes https://trello.com/c/MMGaZQZa/532-okctl-venv-sets-wrong-awsprofile

## How to prove the effect of this PR?

- Set the AWS_PROFILE variable to some value in `.zshrc` / `.bashrc`
- Set a different value for AWS_PROFILE in the current shell
- Run `okctl venv -a aws-profile`
- Observe that the value for AWS_PROFILE in the virtual environment is the same as set in the shell, and not in `.zshrc` / `.bashrc`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the release notes (for the next release).

### CODE REVIEW

**Review by deifyed — CHANGES_REQUESTED** [review]
Something fishy going on with my venv shell now (I use zsh):

PS1 looks used to look like this:
`~/origo/kjøremiljø/iac_tests/julius_iac (julius-d:default) $`
now it looks like this:
`~/origo/kjøremiljø/iac_tests/julius_iac ($(venv_ps1 julius-d)) $` in other words, cluster context / namespace doesn't work

Also my aliases dont work:
```shell
# Master
~/origo/kjøremiljø/iac_tests/julius_iac (julius-d:default) $ which kns
kns: aliased to kubens
~/origo/kjøremiljø/iac_tests/julius_iac (julius-d:default) $ which kwatch
kwatch: aliased to watch kubectl get pods

# This branch
~/origo/kjøremiljø/iac_tests/julius_iac ($(venv_ps1 julius-d)) $ which kns
kns not found
~/origo/kjøremiljø/iac_tests/julius_iac ($(venv_ps1 julius-d)) $ which kwatch
kwatch not found
```

I also get an error when exiting venv:
```shell
# Master
~/origo/kjøremiljø/iac_tests/julius_iac (julius-d:default) $ exit
Exiting okctl virtual environment

# This branch
~/origo/kjøremiljø/iac_tests/julius_iac ($(venv_ps1 julius-d)) $ exit
Error: could not run shell: exit status 127
```

**Review by haavardeide — APPROVED** [review]
Works correctly on Mac Big Sur 11.6 w/zsh 5.8
:shipit: 
```
origo ~/Documents/okctl/h-eide-okctl-config [master] echo $AWS_PROFILE
okctl-prod-admin
origo ~/Documents/okctl/h-eide-okctl-config [master] source ../bin/login-eide-dev-admin.sh
... aws sso loging code
Successully logged into Start URL: https://d-936709095d.awsapps.com/start
origo ~/Documents/okctl/h-eide-okctl-config [master] echo $AWS_PROFILE
okctl-eide-dev-admin
origo ~/Documents/okctl/h-eide-okctl-config [master] /Users/origo/Documents/okctl/okctl/cmd/okctl/okctl venv -c cluster/h-eide-dev/cluster.yaml
... okctl output
~/Documents/okctl/h-eide-okctl-config ($(venv_ps1 h-eide-dev)) $ echo $AWS_PROFILE
okctl-eide-dev-admin
```

Update: did not see the venv_ps1 there, I need to update the colors in iTerm :) 
The problem with running `exit` from venv that @deifyed reported works fine on my machine

**Comment by deifyed** [comment]
Your PS1 is also bugged @haavardeide
> ~/Documents/okctl/h-eide-okctl-config ($(venv_ps1 h-eide-dev)) 

Could you test if your aliases are working?

**Comment by haavardeide** [comment]
@deifyed @fredriv alias does not work here either

**Comment by fredriv** [comment]
Meh, aliases won't work of course if we don't read the config files 😞

**Comment by deifyed** [comment]
Closing this due to no activity

**Pull request closed without merging**
