### PR TITLE
KM260 👌 - use '-f' and not '-c' for cluster reference

### PR DESCRIPTION
**Pull request by haavardeide**
## Description

Use `-f` instead of `-c` for cluster file when running `okctl delete cluster`

## Motivation and Context

Delete is not in the context of a cluster (-c) 

## How to prove the effect of this PR?

* Running `okctl delete cluster -c cluster.yaml`  should result in a error
* Running `okctl delete cluster -f cluster.yaml`  should result in a delete operation 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have updated the release notes (for the next release).

### CODE REVIEW

**Review by deifyed — CHANGES_REQUESTED** [review]
💪💪💪. This should probably be announced since it'l break any systems relying on the API. Speaking of. This PR should include a change to the nightly delete cluster action

**Comment by haavardeide** [comment]
> 💪💪💪. This should probably be announced since it'l break any systems relying on the API. Speaking of. This PR should include a change to the nightly delete cluster action

Yes, we need to announce on support channel!

**Comment by haavardeide** [comment]
Code analysis issue should be solved in a separate issue: https://trello.com/c/vkuUElKa/619-rework-delete-create-cluster-to-use-handler-pattern

**Review by deifyed — APPROVED** [review]
Fire!!

**Comment by yngvark** [comment]
@haavardeide The delete command now uses `--file`, but other commands still use `--cluster-declaration`. Do we have a plan or thoughts about how to deal with this inconcistency?

**Comment by haavardeide** [comment]
> @haavardeide The delete command now uses `--file`, but other commands still use `--cluster-declaration`. Do we have a plan or thoughts about how to deal with this inconcistency?

The plan was not to get rid of `--cluster-declaration`, but to use `--file` in the delete cluster context.

**Comment by yngvark** [comment]
Ah, scratch my comment, there is no inconcistency. I just realized okctl apply cluster always have used `--file`.

**Comment by yngvark** [comment]
@haavardeide The release notes went into 0.0.93, but it should have been insterted into 0.0.94. Can you update please?

**Pull request merged**
