### PR TITLE
22Q2-22 ✅ Bump EKS to 1.20

### PR DESCRIPTION
**Pull request by yngvark**
ToDo:

* [x] Update release notes when releasing with: 

```
22Q2-22 ✅ Bump EKS to 1.20
```

## Description

Changes Okctl to use EKS 1.19 to EKS 1.20.

Changes:
* Knownbinaries: use new version of eksctl and kubectl
* Change to use the new binaries
* Remove from cluster config (used by eksctl): `iam.instanceRolePermissionsBoundary` not used any more, because we've stopped using the `oslokommune-boundary`.
* Node group config: Use 3 node pools, one for each AZ. This setup follows what is described in https://eksctl.io/usage/autoscaling/#zone-aware-auto-scaling. We need this setup, because we are using pods that need to spawn in specificied AZs. They need to be in the same AZ as the PVC they consume, because PVCs are tied to one AZ.
* Removed use of `AuthorizePodToNodeGroupTraffic` because everything works without it. I don't know exactly why, but my theory is that after we removed `dnsPolicy:true` in #764, we don't this anymore.
  * The whole ec2api package is removed as a consequence.
* Bumping VPC CNI addon from default (v1.7.5-eksbuild.2) to 1.11.0-eksbuild.1.

## Motivation and Context

[22Q2-22](https://trello.com/c/ug5bPHVz/22-st%C3%B8tte-eks-120-i-okctl)

## How to prove the effect of this PR?

* Build the project, and create a new cluster with `okctl apply cluster`.
* Launch an application, for instance the okctl reference application, and verify that it works.
* Create a pod that you can exec into and run curl, and verify that `curl http://okctl-reference-app.reference` works.

I have done all these steps to test that everything works.

Also, all our teams have already upgraded to this new setup without any issues, hence we know it should work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
  * Testing is covered by nightly, and manual verification.
- [x] All new and existing tests passed.
- [ ] I have updated the release notes (for the next release).

### CODE REVIEW

**Comment by deifyed** [comment]
I'm getting the following error when trying to create a new cluster:
```
Error: synchronizing declaration with state: reconciling kubernetes cluster: creating cluster: creating cluster: if cluster exists: failed to get cluster information: : executing command: fork/exec /home/deifyed/.okctl/binaries/eksctl/0.98.0/linux/amd64/eksctl: exec format error
```

**Review by deifyed — CHANGES_REQUESTED** [review]
I'd like to figure out the error I experienced before merging this, ref previous comment

**Comment by yngvark** [comment]
I'm guessing `/home/deifyed/.okctl/binaries/eksctl/0.98.0/linux/amd64/eksctl` is 0 bytes - can you check?

(I've seen it before, when the buffer size was less than the file size, but I fixed it by setting buffer size to a greater number than the file size.)

**Comment by deifyed** [comment]
```➜  ~ ll ~/.okctl/binaries/eksctl/0.98.0/linux/amd64
Permissions Size User    Date Modified Name
.rwxr-xr-x     0 deifyed  2 Aug 07:03  eksctl```

**Comment by deifyed** [comment]
```
➜  origo ll ~/.okctl/binaries/eksctl/0.98.0/linux/amd64/
Permissions Size User    Date Modified Name
.rwxr-xr-x  117M deifyed 12 Aug 09:28  eksctl
```
Looks like everything is OK now

**Review by deifyed — APPROVED** [review]

**Pull request merged**
